var database = [
	["0LDT1M3R", "Top"     , "Roosevelt Valor"   , "End Of Empires"    ],
	["0R1G1N4L", "Standard", "Sabre Turbo Custom", ""                  ],
	["1985"    , "Mid"     , "Tropos Rallye"     , "Hip to be Square"  ],
	["1MSORAD" , "Mid"     , "Tropos Rallye"     , ""                  ],
	["2FA5T4U" , "Top"     , "Reaper"            , ""                  ],
	["31GHT135", "Mid"     , "Tropos Rallye"     , ""                  ],
	["4LLOY5"  , "Mid"     , "Seven-70"          , "Shades of Blue"    ],
	["5H0W0FF" , "Mid"     , "Sultan RS"         , ""                  ],
	["5MOOTH"  , "Standard", "Bestia GTS"        , ""                  ],
	["5T34LTH" , "Standard", "Bestia GTS"        , ""                  ],
	["B055"    , "Mid"     , "Massacro"          , "Molten Metal"      ],
	["B0UNC3"  , "Standard", "Sabre Turbo Custom", "Stay Declasse"     ],
	["B1GBOY"  , "Top"     , "ETR1"              , ""                  ],
	["B1GC4T"  , "Mid"     , "Cheetah"           , ""                  ],
	["B1GM0N3Y", "Top"     , "Z-Type"            , "End Of Empires"    ],
	["B35TL4P" , "Top"     , "Tyrus"             , ""                  ],
	["B4N4N4"  , "Mid"     , "Massacro"          , ""                  ],
	["BE4STY"  , "Standard", "Bestia GTS"        , "No Direct Sunlight"],
	["BIGC47"  , "Mid"     , "Cheetah"           , ""                  ],
	["BLKM4MB4", "Top"     , "Mamba"             , "Stay Declasse"     ],
	["BUZZ3D"  , "Mid"     , "Cheetah"           , "Birds Of Paradise" ],
	["C1TRUS"  , "Top"     , "Tyrus"             , "Birds Of Paradise" ],
	["C4TCHM3" , "Top"     , "FMJ"               , "Birds Of Paradise" ],
	["CAR4M3L" , "Top"     , "T20"               , ""                  ],
	["CEO"     , "Top"     , "Z-Type"            , ""                  ],
	["CH4RG3D" , "Standard", "Tampa"             , "Stay Declasse"     ],
	["CL455Y"  , "Mid"     , "Coquette Classic"  , ""                  ],
	["CRU151N" , "Standard", "Tampa"             , ""                  ],
	["CURV35"  , "Mid"     , "Verlierer"         , ""                  ],
	["D0M1N0"  , "Standard", "Banshee 900R"      , ""                  ],
	["D1RTY"   , "Mid"     , "Omnis"             , ""                  ],
	["D34TH4U" , "Top"     , "Reaper"            , "Molten Metal"      ],
	["D3V1L"   , "Top"     , "T20"               , "Uninsurable"       ],
	["DE4DLY"  , "Standard", "Nightshade"        , ""                  ],
	["DR1FT3R" , "Standard", "Banshee 900R"      , "Shades of Blue"    ],
	["E4TME"   , "Standard", "Nightshade"        , ""                  ],
	["F1D3L1TY", "Mid"     , "Sultan RS"         , ""                  ],
	["FRU1TY"  , "Mid"     , "Seven-70"          , ""                  ],
	["FUTUR3"  , "Top"     , "X80 Proto"         , ""                  ],
	["GRIM"    , "Top"     , "Reaper"            , ""                  ],
	["GUNZOUT" , "Standard", "Sabre Turbo Custom", ""                  ],
	["H3RO"    , "Mid"     , "Zentorno"          , ""                  ],
	["HOT4U"   , "Top"     , "FMJ"               , ""                  ],
	["HOTP1NK" , "Standard", "Jester"            , ""                  ],
	["HOWL3R"  , "Standard", "Banshee 900R"      , ""                  ],
	["IML4T3"  , "Mid"     , "Entity XF"         , ""                  ],
	["IN4H4ZE" , "Standard", "Turismo R"         , ""                  ],
	["JOK3R"   , "Top"     , "FMJ"               , ""                  ],
	["K1NGP1N" , "Top"     , "Z-Type"            , ""                  ],
	["K3YL1M3" , "Standard", "Feltzer"           , ""                  ],
	["L4WL355" , "Top"     , "Roosevelt Valor"   , ""                  ],
	["LONG80Y" , "Standard", "Alpha"             , ""                  ],
	["M1DLIFE" , "Top"     , "811"               , ""                  ],
	["M1DN1GHT", "Mid"     , "Cheetah"           , ""                  ],
	["M1LKYW4Y", "Standard", "Turismo R"         , ""                  ],
	["M4K3B4NK", "Top"     , "X80 Proto"         , "Uninsurable"       ],
	["MON4RCH" , "Top"     , "ETR1"              , ""                  ],
	["MU5CL3"  , "Standard", "Tampa"             , ""                  ],
	["N0F00L"  , "Standard", "Jester"            , "Hip to be Square"  ],
	["OBEYM3"  , "Mid"     , "Omnis"             , ""                  ],
	["OH3LLO"  , "Top"     , "Osiris"            , ""                  ],
	["OLDBLU3" , "Top"     , "Mamba"             , ""                  ],
	["OLDN3W5" , "Mid"     , "Zentorno"          , ""                  ],
	["OUTFRONT", "Mid"     , "Verlierer"         , ""                  ],
	["OV3RFL0D", "Mid"     , "Entity XF"         , "Birds Of Paradise" ],
	["P0W3RFUL", "Standard", "Feltzer"           , "No Direct Sunlight"],
	["PH4R4OH" , "Top"     , "Omnis"             , ""                  ],
	["PR3C10US", "Mid"     , "Verlierer"         , "Pastel Perfection" ],
	["PR3TTY"  , "Top"     , "ETR1"              , "Pastel Perfection" ],
	["R31GN"   , "Standard", "Alpha"             , ""                  ],
	["R3G4L"   , "Top"     , "811"               , ""                  ],
	["R4C3R"   , "Standard", "Feltzer"           , ""                  ],
	["R4LLY"   , "Top"     , "Stirling GT"       , "Shades of Blue"    ],
	["SL1CK"   , "Top"     , "811"               , "No Direct Sunlight"],
	["SL33K"   , "Top"     , "Osiris"            , "Uninsurable"       ],
	["SN0WFLK3", "Mid"     , "Sultan RS"         , "Hip to be Square"  ],
	["SP33DY"  , "Mid"     , "Seven-70"          , ""                  ],
	["T0FF33"  , "Mid"     , "Coquette Classic"  , ""                  ],
	["T0PL3SS" , "Mid"     , "Coquette Classic"  , "Pastel Perfection" ],
	["TH370S"  , "Standard", "Nightshade"        , "Fading Power"      ],
	["TOPCLOWN", "Standard", "Jester"            , ""                  ],
	["TOPSP33D", "Top"     , "T20"               , ""                  ],
	["TOUR3R"  , "Top"     , "Stirling GT"       , ""                  ],
	["TPD4WG"  , "Standard", "Turismo R"         , "Shades of Blue"    ],
	["TR3X"    , "Top"     , "Tyrus"             , ""                  ],
	["TROP1CAL", "Standard", "Massacro"          , ""                  ],
	["TURBO"   , "Top"     , "X80 Proto"         , ""                  ],
	["V1NT4G3" , "Mid"     , "Coquette BlackFin" , "Fading Power"      ],
	["V1P"     , "Top"     , "Mamba"             , ""                  ],
	["V1S10NRY", "Standard", "Alpha"             , "Molten Metal"      ],
	["V4LOR"   , "Top"     , "Roosevelt Valor"   , ""                  ],
	["W1D3B0D" , "Top"     , "Omnis"             , "Hip to be Square"  ],
	["W1NN1NG" , "Mid"     , "Zentorno"          , "Molten Metal"      ],
	["W1P3OUT" , "Mid"     , "Coquette BlackFin" , ""                  ],
	["WID3BOY" , "Mid"     , "Entity XF"         , ""                  ],
];
