var database =
[
	['0LDT1M3R', 'Top', 'Roosevelt Valor', '2 driver End Of Empires Collection'],
	['0R1G1N4L', '', 'Sabre Turbo Custom', ''],
	['1985_', 'Mid', 'Tropos Rallye', '4 driver Hip to be Square Collection'],
	['1MSORAD', 'Mid', 'Tropos Rallye', ''],
	['2FA5T4U', 'Top', 'Reaper', ''],
	['31GHT135', 'Mid', 'Tropos Rallye', ''],
	['4LLOY5', 'Mid', 'Seven-70', '4 driver Shades of Blue Collector'],
	['5H0W0FF', 'Mid', 'Sultan RS', ''],
	['5MOOTH', 'Standard', 'Bestia GTS', ''],
	['5T34LTH', 'Standard', 'Bestia GTS', ''],
	['B055', 'Mid', 'Massacro', '4 driver Molten Metal Collection'],
	['B0UNC3', 'Standard', 'Sabre Turbo Custom', '3 driver Stay Declasse Collection'],
	['B1GBOY', 'Top', 'ETR1', ''],
	['B1GC4T', 'Mid', 'Cheetah', ''],
	['B1GM0N3Y', 'Top', 'Z-Type', '2 driver End Of Empires Collection'],
	['B35TL4P', 'Top', 'Tyrus', ''],
	['B4N4N4', 'Mid', 'Massacro', ''],
	['BE4STY', 'Standard', 'Bestia GTS', '3 driver No Direct Sunlight Collection'],
	['BIGC47', 'Mid', 'Cheetah', ''],
	['BLKM4MB4', 'Top', 'Mamba', '3 driver Stay Declasse Collection'],
	['BUZZ3D', 'Mid', 'Cheetah', '4 driver Birds Of Paradise Collection'],
	['C1TRUS', 'Top', 'Tyrus', '4 driver Birds Of Paradise Collection'],
	['C4TCHM3', 'Top', 'FMJ', '4 driver Birds Of Paradise Collection'],
	['CAR4M3L', 'Top', 'T20', ''],
	['CEO', 'Top', 'Z-Type', ''],
	['CH4RG3D', 'Standard', 'Tampa', '3 driver Stay Declasse Collection'],
	['CL455Y', 'Mid', 'Coquette Classic', ''],
	['CRU151N', 'Standard', 'Tampa', ''],
	['CURV35', 'Mid', 'Verlierer', ''],
	['D0M1N0', 'Standard', 'Banshee 900R', ''],
	['D1RTY', 'Mid', 'Omnis', ''],
	['D34TH4U', 'Top', 'Reaper', '4 driver Molten Metal Collection'],
	['D3V1L', 'Top', 'T20', '3 driver Uninsurable Collection'],
	['DE4DLY', 'Standard', 'Nightshade', ''],
	['DR1FT3R', 'Standard', 'Banshee 900R', '4 driver Shades of Blue Collector'],
	['E4TME', 'Standard', 'Nightshade', ''],
	['F1D3L1TY', 'Mid', 'Sultan RS', ''],
	['FRU1TY', 'Mid', 'Seven-70', ''],
	['FUTUR3', 'Top', 'X80 Proto', ''],
	['GRIM', 'Top', 'Reaper', ''],
	['GUNZOUT', 'Standard', 'Sabre Turbo Custom', ''],
	['H3RO', 'Mid', 'Zentorno', ''],
	['HOT4U', 'Top', 'FMJ', ''],
	['HOTP1NK', 'Standard', 'Jester', ''],
	['HOWL3R', 'Standard', 'Banshee 900R', ''],
	['IML4T3', 'Mid', 'Entity XF', ''],
	['IN4H4ZE', 'Standard', 'Turismo R', ''],
	['JOK3R', 'Top', 'FMJ', ''],
	['K1NGP1N', 'Top', 'Z-Type', ''],
	['K3YL1M3', 'Standard', 'Feltzer', ''],
	['L4WL355', 'Top', 'Roosevelt Valor', ''],
	['LONG80Y', 'Standard', 'Alpha', ''],
	['M1DLIFE', 'Top', '811', ''],
	['M1DN1GHT', 'Mid', 'Cheetah', ''],
	['M1LKYW4Y', 'Standard', 'Turismo R', ''],
	['M4K3B4NK', 'Top', 'X80 Proto', '3 driver Uninsurable Collection'],
	['MON4RCH', 'Top', 'ETR1', ''],
	['MU5CL3', 'Standard', 'Tampa', ''],
	['N0F00L', 'Standard', 'Jester', '4 driver Hip to be Square Collection'],
	['OBEYM3', 'Mid', 'Omnis', ''],
	['OH3LLO', 'Top', 'Osiris', ''],
	['OLDBLU3', 'Top', 'Mamba', ''],
	['OLDN3W5', 'Mid', 'Zentorno', ''],
	['OUTFRONT', 'Mid', 'Verlierer', ''],
	['OV3RFL0D', 'Mid', 'Entity XF', '4 driver Birds Of Paradise Collection'],
	['P0W3RFUL', 'Standard', 'Feltzer', '3 driver No Direct Sunlight Collection'],
	['PH4R4OH', 'Top', 'Omnis', ''],
	['PR3C10US', 'Mid', 'Verlierer', '3 driver Pastel Perfection Colletion'],
	['PR3TTY', 'Top', 'ETR1', '3 driver Pastel Perfection Colletion'],
	['R31GN', '', 'Alpha', ''],
	['R3G4L', 'Top', '811', ''],
	['R4C3R', 'Standard', 'Feltzer', ''],
	['R4LLY', 'Top', 'Stirling GT', '4 driver Shades of Blue Collector'],
	['SL1CK', 'Top', '811', '3 driver No Direct Sunlight Collection'],
	['SL33K', 'Top', 'Osiris', '3 driver Uninsurable Collection'],
	['SN0WFLK3', 'Mid', 'Sultan RS', '4 driver Hip to be Square Collection'],
	['SP33DY', 'Mid', 'Seven-70', ''],
	['T0FF33', 'Mid', 'Coquette Classic', ''],
	['T0PL3SS', 'Mid', 'Coquette Classic', '3 driver Pastel Perfection Colletion'],
	['TH370S', 'Standard', 'Nightshade', '2 driver Fading Power Collection'],
	['TOPCLOWN', 'Standard', 'Jester', ''],
	['TOPSP33D', '', 'T20', ''],
	['TOUR3R', 'Top', 'Stirling GT', ''],
	['TPD4WG', 'Standard', 'Turismo R', '4 driver Shades of Blue Collector'],
	['TR3X', 'Top', 'Tyrus', ''],
	['TROP1CAL', 'Standard', 'Massacro', ''],
	['TURBO', 'Top', 'X80 Proto', ''],
	['V1NT4G3', 'Mid', 'Coquette BlackFin', '2 driver Fading Power Collection'],
	['V1P', 'Top', 'Mamba', ''],
	['V1S10NRY', 'Standard', 'Alpha', '4 driver Molten Metal Collection'],
	['V4LOR', 'Top', 'Roosevelt Valor', ''],
	['W1D3B0D', 'Top', 'Omnis', ''],
	['W1NN1NG', 'Mid', 'Zentorno', '4 driver Molten Metal Collection'],
	['W1P3OUT', 'Mid', 'Coquette BlackFin', ''],
	['WID3BOY', 'Mid', 'Entity XF', '4 driver Hip to be Square Collection'],
];
